# Generated by Django 3.2.4 on 2021-06-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(default='', max_length=18, unique=True)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_name', models.BigIntegerField(default=0)),
                ('bank_account', models.IntegerField(default=0)),
                ('bank_agency', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Seller',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SellerContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=100)),
                ('responsible_email', models.EmailField(default='', max_length=200)),
                ('phone_number', models.BigIntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='seller.seller')),
            ],
            options={
                'db_table': 'SellerContact',
                'managed': True,
            },
        ),
    ]
