# Generated by Django 3.2.4 on 2021-06-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
